// Exporter — serialise a Level to a TypeScript source file matching the
// hand-authored ones in src/level/levels/. Numbers are rounded to ≤ 2
// decimal places to keep diffs tidy.

import type { Level, Point } from "../level/Level";

export function exportLevelAsTypeScript(level: Level, id: string): string {
  const varName = id.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
  const t = level.theme;

  const polyStr = (poly: Point[], indent: string): string =>
    poly.map((p) => `${indent}{ x: ${num(p.x)}, y: ${num(p.y)} },`).join("\n");

  const obstacles = level.obstacles.map((poly) =>
    `    [\n${polyStr(poly, "      ")}\n    ],`
  ).join("\n");

  const decorations = (level.decorations ?? []).length
    ? `  decorations: [\n${(level.decorations ?? []).map((d) =>
        `    { type: "${d.type}", x: ${num(d.x)}, y: ${num(d.y)} },`
      ).join("\n")}\n  ],\n`
    : "";

  const checkpoints = (level.checkpoints ?? []).length
    ? `  checkpoints: [\n${(level.checkpoints ?? []).map((c) =>
        `    { x: ${num(c.x)}, y: ${num(c.y)} },`
      ).join("\n")}\n  ],\n`
    : "";

  const waterZones = (level.waterZones ?? []).length
    ? `  waterZones: [\n${(level.waterZones ?? []).map((poly) =>
        `    [\n${polyStr(poly, "      ")}\n    ],`
      ).join("\n")}\n  ],\n`
    : "";

  const spawns = level.spawns.map((sp) =>
    sp.angle !== undefined
      ? `    { x: ${num(sp.x)}, y: ${num(sp.y)}, angle: ${num(sp.angle, 4)} }`
      : `    { x: ${num(sp.x)}, y: ${num(sp.y)} }`
  ).join(",\n");

  return `// ${level.name} — generated by the level editor.
// Paste into src/level/levels/${id}.ts and register in levels/index.ts.

import type { Level } from "../Level";

export const ${varName}: Level = {
  name: ${JSON.stringify(level.name)},
  theme: {
    name: ${JSON.stringify(t.name)},
    skyTop: ${JSON.stringify(t.skyTop)},
    skyBottom: ${JSON.stringify(t.skyBottom)},
    nebula: ${JSON.stringify(t.nebula)},
    starColor: ${JSON.stringify(t.starColor)},
    rockDeepest: ${JSON.stringify(t.rockDeepest)},
    rockDark: ${JSON.stringify(t.rockDark)},
    rockMid: ${JSON.stringify(t.rockMid)},
    rockLight: ${JSON.stringify(t.rockLight)},
    rockRim: ${JSON.stringify(t.rockRim)},
    accent: ${JSON.stringify(t.accent)},
  },
  bounds: { minX: ${level.bounds.minX}, maxX: ${level.bounds.maxX}, minY: ${level.bounds.minY}, maxY: ${level.bounds.maxY} },
  boundary: [
${polyStr(level.boundary, "    ")}
  ],
  obstacles: [
${obstacles}
  ],
  spawns: [
${spawns},
  ],
${decorations}${checkpoints}${waterZones}};
`;
}

function num(v: number, decimals = 2): string {
  const r = Math.round(v * 10 ** decimals) / 10 ** decimals;
  // Strip trailing zeros for tidy diffs.
  return r.toString();
}
